# Reusable file extension check pipeline called by CI pipeline from other repos.
# This YAML will run the file extension check validator on the Pull request.

name: 'File extension check'

on:
  workflow_call:
    secrets:
      GIT_CIT_LOLA_TOKEN:
        required: true

jobs:
  extension_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout worflows repository
      uses: actions/checkout@v2
      with:
        repository: ciandt-abi-lola/lola_workflows
        path: lola_workflows
        token: ${{ secrets.GIT_CIT_LOLA_TOKEN }}

    - name: Running the file extension check
      run: |
         echo '${{ toJSON(github) }}' && sh ${GITHUB_WORKSPACE}/lola_workflows/scripts/extension_check.sh ${{ github.base_ref }}